// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatTextareaController from "./chat_textarea_controller"
application.register("chat-textarea", ChatTextareaController)

import LocationTabsController from "./location_tabs_controller"
application.register("location-tabs", LocationTabsController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import SearchEligibleCountriesController from "./search_eligible_countries_controller"
application.register("search-eligible-countries", SearchEligibleCountriesController)

import SearchLocationsController from "./search_locations_controller"
application.register("search-locations", SearchLocationsController)
